### ISSUE TITLE
ElasticLoadBalancerV2 LoadBalancer did not stabilize.

### ISSUE THREAD

**Issue by jeffbross** [aws-quickstart/quickstart-atlassian-confluence#15]
I am trying to run the exsiting VPC cloud formation and am getting the following error
Note: There is no external access and thus no NATs.
We have successfully completed bitbucket and jira by chaging the scheme to internal, but confluence template does not have this option.

Please help..

ElasticLoadBalancerV2 LoadBalancer did not stabilize.
--

**Comment by avattathil** [comment]
Please reopen if this issue is still relevant in latest master
