### ISSUE TITLE
Targets pointing to EC2 show unhealthy

### ISSUE THREAD

**Issue by stelang** [aws-quickstart/quickstart-atlassian-confluence#18]
Hi @avattathil When I run the quickstart CFT the ec2 node shows in running state but something seems wrong in the way confluence is installed on the node from the base_ami. Target group shows that hosts are unhealthy. I'm trying to install version 6.8.1. ssh'ing on the box showed me that there was no confluence running and directory structure seemed messed up. For e.g. /var/attlasian/application-date/ did not have confluence directory in it. Has something changed in the image because this worked for me last friday. The ami in the current template code for us-east-1 is ami-80d6f1fb. It used to use ami-bcc091c6 when it was working fine. I tried using ami-bcc091c6 to recreate stack but I have the same issue.

**Comment by stelang** [comment]
Update: after checking the cfn-init.lg file it looks like it could not find collectd and failed to install confluence. So this means your template will break for the image specified in us-east-1

**Comment by avattathil** [comment]
This issue should be resolve by #23 Which updates the some lost changes. Please reopen is issue persists
