### ISSUE TITLE
Confluence CloudFormation templates out dated

### ISSUE THREAD

**Issue by vhu94** [aws-quickstart/quickstart-atlassian-confluence#21]
Hey @avattathil, 

I'm from the Atlassian team, and it's just come to our attention that the CF template here no longer corresponds to our internal Atlassian one and that some of our customers are having issues spinning up Confluence from the AWS linked CF template.  I noticed that the parent of [this commit](https://github.com/aws-quickstart/quickstart-atlassian-confluence/commit/2d5e354037d0c28549898cfd727257468eadbd46) is from a PR that was merged back in August 2017. Upon closer inspection of the file histories of `ConfluenceDataCenter.template` and `quickstart-confluence-master.template`, the changes from around August 2017 up until this commit seem to have disappeared. I don't have permissions to raise a PR in the repo at the moment, but do you have any idea about what might have happened?

Thanks,

Vivian

**Comment by avattathil** [comment]
Resolved with #23
